export const exportReport = (analysis) => {
  if (!analysis) return;

  const formatCurrency = (value) => `$${parseFloat(value).toFixed(2)}`;
  const formatPercent = (value) => `${parseFloat(value).toFixed(1)}%`;

  const content = `AI ECOMMERCE SWOT ANALYSIS REPORT
================================================================

Report Generated: ${new Date().toLocaleString()}
Analysis Engine: Gemini AI
Data Sources: ${analysis.allMetrics.length} dataset(s)

================================================================
EXECUTIVE SUMMARY
================================================================

${analysis.swot.keyInsights}

================================================================
KEY METRICS OVERVIEW
================================================================

FINANCIAL METRICS:
• Total Revenue: ${formatCurrency(analysis.metrics.totalRevenue)}
• Total Orders: ${analysis.metrics.totalOrders}
• Average Order Value: ${formatCurrency(analysis.metrics.avgOrderValue)}
• Revenue Growth Trend: ${analysis.metrics.growthTrend}

OPERATIONAL METRICS:
• Return Rate: ${formatPercent(analysis.metrics.returnRate)}
• Payment Failure Rate: ${formatPercent(analysis.metrics.failureRate)}
• Total Products: ${analysis.metrics.totalProducts}
• Total Customers: ${analysis.metrics.totalCustomers || 'N/A'}
• Repeat Purchase Rate: ${formatPercent(analysis.metrics.repeatPurchaseRate || 0)}

TOP PERFORMING PRODUCTS:
${analysis.metrics.topProducts.map((product, i) => `  ${i+1}. ${product}`).join('\n')}

================================================================
PREDICTIVE ANALYSIS
================================================================

FORECASTS:
• Next Month Revenue Forecast: ${formatCurrency(analysis.predictions.forecast)}
• Growth Rate: ${formatPercent(analysis.predictions.growthRate)}
• Volatility: ${formatPercent(analysis.predictions.volatility)}
• Risk Level: ${analysis.predictions.riskLevel}
• Seasonal Pattern: ${analysis.predictions.seasonalPattern}

PREDICTIVE INSIGHTS:
${analysis.swot.predictiveInsights}

================================================================
SWOT ANALYSIS
================================================================

STRENGTHS:
${analysis.swot.strengths.map((s, i) => `  ${i+1}. ${s}`).join('\n')}

WEAKNESSES:
${analysis.swot.weaknesses.map((w, i) => `  ${i+1}. ${w}`).join('\n')}

OPPORTUNITIES:
${analysis.swot.opportunities.map((o, i) => `  ${i+1}. ${o}`).join('\n')}

THREATS:
${analysis.swot.threats.map((t, i) => `  ${i+1}. ${t}`).join('\n')}

================================================================
STRATEGIC RECOMMENDATIONS
================================================================

${analysis.swot.recommendations.map((r, i) => `  ${i+1}. ${r}`).join('\n')}

================================================================
COMPETITIVE POSITIONING
================================================================

${analysis.swot.competitivePosition}

${analysis.isComparison ? `\nDATASET COMPARISON:
${analysis.allMetrics.map((m, i) => `
Dataset ${i+1}: ${m.name}
  • Revenue: ${formatCurrency(m.metrics.totalRevenue)}
  • Orders: ${m.metrics.totalOrders}
  • AOV: ${formatCurrency(m.metrics.avgOrderValue)}
  • Return Rate: ${formatPercent(m.metrics.returnRate)}
  • Failure Rate: ${formatPercent(m.metrics.failureRate)}`).join('\n')}
` : ''}

================================================================
CATEGORY PERFORMANCE
================================================================

${Object.entries(analysis.metrics.categoryRevenue)
  .sort((a, b) => b[1] - a[1])
  .map(([category, revenue]) => `• ${category}: ${formatCurrency(revenue)}`)
  .join('\n')}

================================================================
REPORT FOOTER
================================================================

Generated by AI eCommerce SWOT Analyzer
© ${new Date().getFullYear()} - For strategic business decisions
Recommendations should be reviewed by business stakeholders`;

  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `SWOT_Analysis_Report_${new Date().toISOString().slice(0, 10)}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};